In [1]:
import pandas as pd

In [3]:
products = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample good/Products.csv")

In [17]:
print(products.head())

  product_id  product_name  product_category   unit_price   reorder_level   \
0        P001     USB cable       Electronics          666              30
1        P002    Headphones       Electronics          932              25
2        P003         Mouse       Electronics          350              20
3        P004     Rice 10Kg           Grocery          579              28
4        P005   Sugar 500gm           Grocery           36              45

   lead_time_days
0                4
1                6
2                7
3                3
4                2

In [9]:
print(products.shape)

(10, 6)

In [10]:
print(products.columns)

Index(['product_id ', 'product_name ', 'product_category ', 'unit_price ',
       'reorder_level ', 'lead_time_days '],
      dtype='object')

In [11]:
print(products.dtypes)

product_id           object
product_name         object
product_category     object
unit_price            int64
reorder_level         int64
lead_time_days        int64
dtype: object

In [13]:
print(products.describe())

       unit_price   reorder_level   lead_time_days
count    10.000000        10.00000         10.00000
mean    450.200000        28.30000          3.80000
std     329.474599        13.12377          1.75119
min      36.000000        10.00000          2.00000
25%     121.250000        20.00000          2.25000
50%     503.000000        26.50000          3.50000
75%     644.250000        37.50000          4.75000
max     932.000000        50.00000          7.00000

In [14]:
sales = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample good/Sales.csv")

In [19]:
print(sales.head())

  sale_id  product_id            sale_date   quantity_sold
0     S001        P005  2026-09-05 17:32:15               1
1     S002        P005  2026-09-05 17:40:09               2
2     S003        P003  2026-09-05 17:53:48               1
3     S004        P004  2026-09-05 18:12:06               1
4     S005        P001  2026-09-05 18:40:03               1

In [16]:
print(sales.shape)

(30, 4)

In [20]:
print(sales.columns)

Index(['sale_id ', 'product_id ', 'sale_date ', 'quantity_sold '], dtype='object')

In [21]:
print(sales.dtypes)

sale_id           object
product_id        object
sale_date         object
quantity_sold      int64
dtype: object

In [25]:
print(sales.describe())

       quantity_sold
count       30.000000
mean         1.600000
std          1.003442
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          5.000000

In [26]:
inventory = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample good/Inventory.csv")

In [28]:
print(inventory.head())

  product_id   current_stock
0        P001              12
1        P002              15
2        P003              10
3        P004              17
4        P005               4

In [29]:
print(inventory.dtypes)

product_id        object
current_stock      int64
dtype: object

In [30]:
bad_data_products =pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample bad/Products.csv")

In [33]:
print(bad_data_products)

   product_id       product_name  product_category   unit_price   \
0         P001          USB cable       Electronics        666.0
1         P002         Headphones       Electronics        932.0
2         P003              Mouse       Electronics          0.0
3         P004          Rice 10Kg           Grocery        579.0
4          NaN        Sugar 500gm           Grocery        -36.0
5         P006  Wheat flour 500gm           Grocery         38.0
6         P007       Bucket combo         Household        486.0
7         P008       Home Cleaner         Household        520.0
8         P009       3Broom stick         Household        850.0
9          NaN      Snickers 50gm            Snacks        -45.0
10        P009       3Broom stick         Household        850.0
11        P009       3Broom stick         Household        850.0
12         NaN                NaN               NaN          NaN
13        P013  Wheat flour 500gm           Grocery         38.0

    reorder_level   lead_time_days
0             30.0              4.0
1             25.0              6.0
2             20.0              7.0
3             28.0              3.0
4             45.0              2.0
5             40.0              2.0
6             20.0              4.0
7             15.0              3.0
8             10.0              0.0
9             50.0              2.0
10            10.0              0.0
11            10.0              0.0
12             NaN              NaN
13            40.0              2.0

In [34]:
bad_data_products.isnull().sum()

product_id           3
product_name         1
product_category     1
unit_price           1
reorder_level        1
lead_time_days       1
dtype: int64

In [41]:
bad_data_products.columns

Index(['product_id ', 'product_name ', 'product_category ', 'unit_price ',
       'reorder_level ', 'lead_time_days '],
      dtype='object')

In [45]:
bad_data_products["product_id "].duplicated().sum()

np.int64(4)

In [46]:
bad_data_products.columns.tolist()

['product_id ',
 'product_name ',
 'product_category ',
 'unit_price ',
 'reorder_level ',
 'lead_time_days ']

In [48]:
bad_data_products.columns.str.strip().tolist()

['product_id',
 'product_name',
 'product_category',
 'unit_price',
 'reorder_level',
 'lead_time_days']

In [55]:
bad_data_products[bad_data_products["product_id "].duplicated(keep = False)]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
4,NaN,Sugar 500gm,Grocery,-36.0,45.0,2.0
8,P009,3Broom stick,Household,850.0,10.0,0.0
9,NaN,Snickers 50gm,Snacks,-45.0,50.0,2.0
10,P009,3Broom stick,Household,850.0,10.0,0.0
11,P009,3Broom stick,Household,850.0,10.0,0.0
12,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
bad_data_products.columns.equals(bad_data_products.columns.str.strip())

False

In [59]:
bad_data_products[bad_data_products["lead_time_days "] <=0]

,product_id,product_name,product_category,unit_price,reorder_level,lead_time_days
8,P009,3Broom stick,Household,850.0,10.0,0.0
10,P009,3Broom stick,Household,850.0,10.0,0.0
11,P009,3Broom stick,Household,850.0,10.0,0.0

In [61]:
bad_data_sales = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample bad/Sales.csv")

In [62]:
bad_data_sales[~bad_data_sales["product_id "].isin(bad_data_products["product_id "])]

   sale_id  product_id            sale_date   quantity_sold
0      S001        P005  2026-09-05 17:32:15               1
1      S002        P005  2026-09-05 17:40:09               2
17     S018        P010  2026-09-07 22:40:09               4
22     S023        P010  2026-09-08 23:51:01               2
24     S025        P010  2026-09-09 10:53:48               3
27     S028        P005  2026-09-09 11:48:27               2

In [63]:
bad_data_inventory = pd.read_csv("C:/Users/admin/OneDrive/Desktop/smart-inventory/data/raw/Sample bad/Inventory.csv")

In [65]:
bad_data_inventory[bad_data_inventory["current_stock "] > 0]

  product_id   current_stock
0        P001              12
1        P002              15
2        P003              10
3        P004              17
4        P005               4
5        P006               2
6        P007               6
7        P008               9
8        P009              10
9        P010               1